# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# Trigger on any branch not just main
trigger:
  - "*"

# This makes sure we have a linux image with npm installed
pool:
  vmImage: "ubuntu-20.04"
  demands:
    - npm

variables:
  buildConfiguration: Release
  wwwrootDir: "Tailspin.SpaceGame.Web/wwwroot"
  dotnetSdkVersion: "5.x"

steps:
  # This makes sure we have the full DotNet SDK
  - task: UseDotnet@2
    displayName: "Use .NET SDK $(dotnetSdkVersion)"
    inputs:
      packageType: sdk
      version: "$(dotnetSdkVersion)"

  # This makes sure we run npm install
  - task: Npm@1
    displayName: "Run npm install"
    inputs:
      verbose: false

  # Here we have a custom command to compile CSS
  - script: "./node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)"
    displayName: "Compile Sass assets"

  - task: gulp@1
    displayName: "Run gulp tasks"

  - script: 'echo "$(Build.DefinitionName), $(Build.buildId), $(Build.buildNUmber)" > buildinfo.txt'
    displayName: "Write build info"
    workingDirectory: $(wwwrootDir)

  - task: DotNetCoreCLI@2
    displayName: "Restore project dependencies"
    inputs:
      command: "restore"
      projects: "**/*.csproj"

  - template: templates/build.yaml
    parameters:
      buildConfiguration: "Debug"

  - template: templates/build.yaml
    parameters:
      buildConfiguration: "Release"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    condition: succeeded()
